@echo off

SET RELEASE32=release\task-1.exe
SET RELEASE64=x64\release\task-1.exe
SET DEBUG32=debug\task-1.exe
SET DEBUG64=x64\debug\task-1.exe

IF EXIST %RELEASE64% (
	ECHO RELEASEx64
    SET PROG=%RELEASE64%
) ELSE IF EXIST %RELEASE32% (
	ECHO RELEASEx32
	SET PROG=%RELEASE32%
) ELSE IF EXIST %DEBUG64% (
	ECHO DEBUGx64
	SET PROG=%DEBUG64%
) ELSE IF EXIST %DEBUG32% (
	ECHO DEBUGx32
	SET PROG=%DEBUG32%
) ELSE (
	ECHO EXECUTABLE FILE ISN'T FOUND
	PAUSE
	EXIT /B 1
)
::SET PROG=debug\task-1

:: TEST#1
SET OP=+
SET OP1=38
SET OP2=4
CALL :CHECK OP1 OP OP2
:: TEST#2
SET OP=-
SET /A OP1=%OP1%*2
SET /A OP2=%OP2%*%OP2%
CALL :CHECK OP1 OP OP2
:: TEST#3
SET OP=*
SET /A OP1=%OP1%-536
SET /A OP2=%OP2%/4
CALL :CHECK OP1 OP OP2
:: TEST#4
SET OP=/
SET /A OP1=%OP1%*3
SET /A OP2=%OP2%+67
CALL :CHECK OP1 OP OP2
:: TEST#5
SET OP=%%
SET /A OP1=%OP1%*2
SET /A OP2=%OP2%*%OP2%
CALL :CHECK OP1 OP OP2
:: TEST#6
SET OP="^"
SET OP1=2
SET OP2=13
SET ANS=8192
FOR /F %%i in ('%PROG% %OP1% %OP% %OP2%') DO SET RES=%%i
IF %RES% EQU %ANS% (
ECHO PASSED:	%OP1% ^^ %OP2% = %RES%
) ELSE (ECHO FAILED:	%OP1% ^^ %OP2% = %RES%)

PAUSE

:CHECK OP1 OP OP2
SET /A ANS=%OP1%%OP%%OP2%
FOR /F %%i in ('%PROG% %OP1% %OP% %OP2%') DO SET RES=%%i
SET PASSED=PASSED:	%OP1% %OP% %OP2% = %RES%
SET WRONG=FAILED:	%OP1% %OP% %OP2% = %RES%
IF %RES% EQU %ANS% (ECHO %PASSED%) ELSE (ECHO %WRONG%)
EXIT /B 0