:: THIS SCRIPT WORKS ONLY FOR WIN10 AND ISN'T READY
@echo off
SETLOCAL
CALL :setESC

SET PROG=task-1

:: TEST#1
SET OP=+
SET OP1=38
SET OP2=4
CALL :CHECK OP1 OP OP2
:: TEST#2
SET OP=-
SET /A OP1=%OP1%*2
SET /A OP2=%OP2%*%OP2%
CALL :CHECK OP1 OP OP2
:: TEST#3
SET OP=*
SET /A OP1=%OP1%-536
SET /A OP2=%OP2%/100
:: TEST#4
SET OP=/
SET /A OP1=%OP1%*3
SET /A OP2=%OP2%+67
CALL :CHECK OP1 OP OP2
:: TEST#5
SET OP=%
SET /A OP1=%OP1%*2
SET /A OP2=%OP2%*%OP2%
CALL :CHECK OP1 OP OP2
:: TEST#6
SET OP=^
SET OP1=2
SET OP2=10
CALL :CHECK OP1 OP OP2

ECHO %ESC%[0m
PAUSE

:CHECK OP1 OP OP2
:: TODO ADD CORRECT PROCESSING OPERATIONS % AND ^
::IF "%2" == "%" (SET /A ANS=%1%%%3) ELSE (SET /A ANS=%OP1%%OP%%OP2%)
SET /A ANS=%OP1%%OP%%OP2%
FOR /f %%i in ('%PROG% %OP1% %OP% %OP2%') DO SET RES=%%i
IF %RES% EQU %ANS% (ECHO %ESC%[32m) ELSE (ECHO %ESC%[31m)
ECHO %OP1% %OP% %OP2% = %RES% %ESC%[0m
EXIT /B 0

:POW NUMBER POWER RESULT
SET %~3=1
FOR /L %%i IN (1,1,%2) DO SET /A %~3=%3*%1
EXIT /B 0

:setESC
FOR /F "tokens=1,2 delims=#" %%a IN ('"PROMPT #$H#$E# & ECHO on & FOR %%b in (1) DO rem"') DO (
  SET ESC=%%b
  EXIT /B 0
)